# Basic site info
title: "Mohamed Elhassan"
description: "Bachelor of Computer Science | Full‑Stack Dev & Cloud Engineer"
url: "https://mohamed-elhassan.github.io/CapStone"
baseurl: ""                                      

# Theme & plugins
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
permalink: /:title/

# Navigation menu
navbar:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Optional analytics
google_analytics: 

# Hide Cayman’s “Downloads” section
show_downloads: false

exclude:
  - README.md
  - node_modules
  - vendor

theme: jekyll-theme-cayman
